const root=document.getElementById('root'),stage=document.getElementById('stage'),card=document.getElementById('instruction'),toast=document.getElementById('toast');let scene=0,pass='',audio=false;const name='YOU',code='0716';const copy=['Pull the drifting crate toward the shore.','Tap the brass latch.','Drag to rotate and inspect the chest, then tap it open.','Enter the birthday as the passcode.','Peel the wax seal from the velvet envelope.','Drag downward to unfold the handwritten letter.','Tap the paper crane and follow its flight.','Tap the boy until he leaves the panel.',`Watch the stars gather into HAPPY BIRTHDAY, ${name}.`];
function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}function make(tag,cls,html=''){const n=document.createElement(tag);n.className=cls;n.innerHTML=html;root.appendChild(n);return n}function next(){scene++;render()}function clear(){root.innerHTML='';stage.className='stage';stage.style.background=''}function render(){clear();card.textContent=copy[scene];[ocean,latch,inspect,safe,seal,letter,crane,duo,stars][scene]()}function drag(n,fn){let sx=0,sy=0,ox=0,oy=0;n.addEventListener('pointerdown',e=>{n.setPointerCapture(e.pointerId);sx=e.clientX;sy=e.clientY;const m=new DOMMatrixReadOnly(getComputedStyle(n).transform);ox=m.m41;oy=m.m42});n.addEventListener('pointermove',e=>{if(!n.hasPointerCapture(e.pointerId))return;const dx=e.clientX-sx,dy=e.clientY-sy;n.style.transform=`translate(${ox+dx}px,${oy+dy}px) rotate(${dx/18}deg)`;fn(dx,dy,n)});n.addEventListener('pointerup',e=>n.releasePointerCapture(e.pointerId))}
function ocean(){const c=make('div','obj crate');make('button','egg pen').dataset.msg='A forgotten pen has already written the ending.';drag(c,(dx,dy,n)=>{if(dx<-90&&dy>25){n.style.transition='transform .7s cubic-bezier(.2,1.4,.3,1)';n.style.transform='translate(-135px,54px) rotate(-4deg)';setTimeout(next,720)}})}
function latch(){const c=make('div','obj chest','<div class="latch"></div>');make('button','egg ticket').dataset.msg='An old bus ticket: one way to a better year.';c.onclick=()=>{c.classList.add('open');flash();setTimeout(next,900)}}
function inspect(){let rot=0,opened=false;const c=make('div','obj chest','<div class="latch"></div>');drag(c,(dx,dy,n)=>{rot=Math.max(-28,Math.min(28,dx/3));n.style.transform=`translateX(-50%) rotateY(${rot}deg) rotate(${rot/8}deg)`});c.onclick=()=>{if(Math.abs(rot)>8&&!opened){opened=true;c.classList.add('open');setTimeout(next,800)}else say('Let the chest catch the moonlight first.')}}
function safe(){pass='';const s=make('div','obj safe','<div class="dial"></div><div class="display">----</div><div class="keypad"></div>'),pad=s.querySelector('.keypad'),display=s.querySelector('.display');'1234567890'.split('').forEach(x=>{const b=document.createElement('button');b.textContent=x;b.onclick=()=>{pass=(pass+x).slice(-4);display.textContent=pass.padEnd(4,'-');tone();if(pass===code){display.textContent='OPEN';flash();setTimeout(next,650)}};pad.appendChild(b)})}
function seal(){const e=make('div','obj envelope','<div class="seal"></div>'),s=e.querySelector('.seal');drag(s,(dx,dy,n)=>{if(Math.hypot(dx,dy)>90){n.style.transition='transform .6s ease';n.style.transform='translate(120px,-90px) rotate(35deg) scale(.65)';setTimeout(next,700)}})}
function letter(){const l=make('div','obj letter','Dear you,<br><br>May this year unfold like a secret page: quietly, bravely, and full of impossible light.');drag(l,(dx,dy,n)=>{if(dy>115){n.style.transition='transform .8s cubic-bezier(.2,1.4,.3,1)';n.style.transform='translate(-50%,40px) scaleY(1.18)';setTimeout(next,800)}})}
function crane(){const c=make('div','obj crane');c.onclick=()=>{c.style.transition='transform 1.8s cubic-bezier(.2,.9,.2,1)';c.style.transform='translate(120px,-360px) rotate(28deg)';setTimeout(next,1400)}}
function duo(){stage.classList.add('duo');make('div','ground');make('div','person girl','<i></i>');const boy=make('div','person boy'),tap=make('div','tap'),bouquet=make('div','bouquet');make('div','grenade');make('div','boom');let t=0;function advance(){t++;boy.style.transform=`translateX(${t*58}px) rotate(${t*3}deg)`;if(t===1)say('The panel stretches with the silence.');if(t>=4){root.classList.add('throw');setTimeout(()=>root.classList.add('explode'),1000);setTimeout(()=>bouquet.classList.add('show'),1550);setTimeout(next,3000)}}boy.onclick=advance;tap.onclick=advance}
function stars(){stage.style.background='#08090f';const wrap=make('div','stars');for(let i=0;i<95;i++){const s=document.createElement('i');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*2+'s';wrap.appendChild(s)}make('div','birthday',`HAPPY<br>BIRTHDAY<span>${name}</span>`)}function flash(){stage.animate([{filter:'brightness(1)'},{filter:'brightness(1.7)'},{filter:'brightness(1)'}],{duration:620,easing:'ease-out'})}function tone(){if(!audio)return;const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=220;g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.13)}
document.addEventListener('click',e=>{const egg=e.target.closest('[data-msg]');if(egg)say(egg.dataset.msg)});document.getElementById('hint').onclick=()=>say(copy[scene]);document.getElementById('sound').onclick=e=>{audio=!audio;e.target.textContent=`sound: ${audio?'on':'off'}`;tone()};render();
